container:
  image: python:3.6

check_task:
  install_script: pip install --upgrade pip && pip install -r requirements.txt
  test_script: make test
  lint_script: make check
  coverage_script: make coverage
  codecov_script: bash <(curl -s https://codecov.io/bash) -t 0660129b-fb9f-427c-a587-1fa37508c42c
