version: '3.5'
services:
  app:
    image: ceumanti/docker-python-odbc:latest
    container_name: flaskeleton
    restart: on-failure:10
    volumes:
      - .:/application
      - /var/log/flaskeleton-api/:/application/logs/
    command: bash -c "chmod +x run.sh && ./run.sh"
    ports:
      - "5000:5000"