version: '3.5'
services:
  app:
    build: .
    container_name: flaskeleton
    restart: on-failure:10
    volumes:
      - .:/application
    command: "gunicorn --workers=4 --bind=0.0.0.0:${FLASKELETON_PORT_CONTAINER} --log-level=info  app:'create_app()'"
    ports:
      - "${FLASKELETON_PORT_HOST}:${FLASKELETON_PORT_CONTAINER}"