version: '3.5'
services:
  app:
    build: .
    container_name: flaskeleton
    restart: on-failure:10
    volumes:
      - .:/application
    command: "gunicorn  --worker-class gevent --workers=4 --threads 2 --bind=0.0.0.0:5000 --log-level=info app:'create_app()'"
    ports:
      - "3000:5000"
    environment:
      - DATABASE_URI=sqlite:////application/flaskeleton.db
      - DATABASE_DEV=sqlite:////application/flaskeleton.db
      - DATABASE_PROD=sqlite:////application/production.db
