version: '3.5'
services:
  app:
    build: .
    container_name: flaskeleton
    restart: on-failure:10
    volumes:
      - .:/application
    command: gunicorn --workers=4 --bind=0.0.0.0:${PORT} --log-level=info  app:'create_app()'
    ports:
      - "5000:5000"